"""
TELEGRAM BOT for NSE Stock Scanner
Will send scanner results to your Telegram
"""
import requests
import json
import time
from datetime import datetime

class TelegramStockBot:
    """
    Sends stock alerts to Telegram
    """
    
    def __init__(self, bot_token, chat_id):
        self.bot_token = bot_token
        self.chat_id = chat_id
        self.base_url = f"https://api.telegram.org/bot{bot_token}"
        
        print("🤖 Telegram Bot Initialized")
        print(f"Chat ID: {chat_id}")
    
    def send_message(self, text, parse_mode="HTML"):
        """
        Send message to Telegram
        """
        url = f"{self.base_url}/sendMessage"
        payload = {
            "chat_id": self.chat_id,
            "text": text,
            "parse_mode": parse_mode,
            "disable_web_page_preview": True
        }
        
        try:
            response = requests.post(url, json=payload, timeout=10)
            if response.status_code == 200:
                print(f"✅ Message sent: {text[:50]}...")
                return True
            else:
                print(f"❌ Failed to send: {response.text}")
                return False
        except Exception as e:
            print(f"❌ Error: {e}")
            return False
    
    def send_scanner_results(self, stocks_data):
        """
        Send formatted scanner results
        """
        if not stocks_data:
            self.send_message("📊 No stocks passed the scanner today.")
            return
        
        # Create formatted message
        message = "📈 <b>NSE SCANNER RESULTS</b>\n"
        message += f"📅 {datetime.now().strftime('%d %b %Y %H:%M')}\n"
        message += f"✅ Found: {len(stocks_data)} stocks\n\n"
        
        # Add top 5 stocks
        for i, stock in enumerate(stocks_data[:5], 1):
            message += f"<b>{i}. {stock['symbol']}</b>\n"
            message += f"   Name: {stock['name']}\n"
            message += f"   Price: ₹{stock.get('current_price', 0):.2f}\n"
            message += f"   Change: {stock.get('price_change', 0):+.2f}%\n"
            
            # Add TradingView link
            tv_link = f"https://www.tradingview.com/chart/?symbol=NSE:{stock['symbol']}"
            message += f"   Chart: <a href='{tv_link}'>View</a>\n\n"
        
        if len(stocks_data) > 5:
            message += f"... and {len(stocks_data) - 5} more stocks.\n"
        
        message += "\n⚡ <i>Auto-generated by NSE Scanner</i>"
        
        # Send message
        self.send_message(message)
    
    def send_test_alert(self):
        """
        Send a test alert
        """
        test_stocks = [
            {
                'symbol': 'RELIANCE',
                'name': 'Reliance Industries',
                'current_price': 2850.50,
                'price_change': 1.25,
                'wmas': {'daily_wma_1': 2845, 'monthly_wma_2': 2820}
            },
            {
                'symbol': 'TCS',
                'name': 'Tata Consultancy Services',
                'current_price': 4150.75,
                'price_change': 0.85,
                'wmas': {'daily_wma_1': 4140, 'monthly_wma_2': 4100}
            }
        ]
        
        print("🧪 Sending test alert...")
        self.send_scanner_results(test_stocks)
    
    def get_bot_info(self):
        """
        Test bot connection
        """
        url = f"{self.base_url}/getMe"
        try:
            response = requests.get(url, timeout=10)
            if response.status_code == 200:
                data = response.json()
                print(f"✅ Bot connected: {data['result']['username']}")
                return True
            else:
                print(f"❌ Bot connection failed")
                return False
        except Exception as e:
            print(f"❌ Error: {e}")
            return False

# TEST THE BOT
if __name__ == "__main__":
    print("="*50)
    print("🤖 TELEGRAM BOT TEST")
    print("="*50)
    
    # YOUR CREDENTIALS (replace with yours)
    BOT_TOKEN = "8289967600:AAFSLnB1eCSYpKOdIenz398AcdJ5utcNyIs"
    CHAT_ID = "810052560"
    
    # Initialize bot
    bot = TelegramStockBot(BOT_TOKEN, CHAT_ID)
    
    # Test connection
    print("\n1. Testing bot connection...")
    if bot.get_bot_info():
        print("✅ Bot is LIVE and connected!")
    else:
        print("❌ Check your bot token")
        exit()
    
    # Send test message
    print("\n2. Sending test message...")
    bot.send_message("🔔 <b>NSE Scanner Bot Activated!</b>\n"
                    f"Time: {datetime.now().strftime('%H:%M:%S')}\n"
                    "This bot will send daily scanner results.")
    
    # Send test alert (sample scanner results)
    print("\n3. Sending sample scanner results...")
    bot.send_test_alert()
    
    print("\n" + "="*50)
    print("🎉 TELEGRAM BOT IS WORKING!")
    print("On Feb 6th, this bot will send REAL scanner results!")
    print("="*50)